### ISSUE TITLE
Return a value 

### ISSUE THREAD

**Issue by slowflyer** [stegm/pykoplenti#1]
Hi,

would be great if 
`    async def set_setting_values(self, module_id: str, values: Dict[str, str]):
        """Writes a list of settings for one modules."""
        request = [
            {
                "moduleid": module_id,
                "settings": list([dict(value=v, id=k) for k, v in values.items()]),
            }
        ]
        async with self._session_request(
            "settings", method="PUT", json=request
        ) as resp:
            await self._check_response(resp)`

would return a boolean value for success on updating the value or not.

**Comment by stegm** [comment]
The method returns nothing for success and throws an exception on failure. If you want a boolean you have to wrap it into try/except, e.g.:

```python
try:
  client.set_setting_value(....)
except:
  return False
else:
  return True
```

**Comment by slowflyer** [comment]
Thanks!
