### ISSUE TITLE
pydantic > 2

### ISSUE THREAD

**Issue by fabaff** [stegm/pykoplenti#12]
The current constraint on `pydantic` doesn't allow releases >= 2. 

Migration guide: https://docs.pydantic.dev/2.0/migration/

The missing support for `pydantic`>= 2 could become an issue for Home Assistant users.

**Comment by stegm** [comment]
When I switched to pydantic model, I first use 2.0 but then I saw that home assistant uses 1.10. Unfortunately I have to change something in code in pydantic >2.

So is there are plan how to switch and still staying backward compatible?

**Comment by fabaff** [comment]
Perhaps https://pypi.org/project/pydantic-compat/ could help?
