### ISSUE TITLE
Change the host / ip of my inverter in Home Assistant

### ISSUE THREAD

**Issue by Acanis87** [stegm/pykoplenti#14]
Hey, 

Iam not sure, if Iam right here...^^ Your profile was linked as integration owner (https://www.home-assistant.io/integrations/kostal_plenticore) and thats your repo regarding Kostal Inverter readings.

I changed my router and after that the integration wasnt working, since the inverter got a new ip adress. I dont want to lose the data of my entities, but I also dont know my old ip adress and I cant change the ip adress for the integration somewhere?! 

What can I do? :)

**Comment by stegm** [comment]
Hey Acanis87, 

I had to change the IP of my inverter in the past too. I worked without a problem, just delete the inverter and create it again. as long as the inverter have the same name (default: scb) everythings works as before.

There might be an alternative: The ip is saved in the config/.storage/core.device_registry file, where you can edit it directly. Just make sure, homeassistant is stopped.

Whatever way you choose: Make a backup of your homeassistant configuration before.
