### ISSUE TITLE
Use on wich interface

### ISSUE THREAD

**Issue by Slamkryp** [stegm/pykoplenti#9]
Hi,

Sorry to do like this but witch interface on a kostal 50 ci inverter can you use this api?

Is it on all interfaces or only on wifi AP, wifi STA or Ethernet?

Best regards!

**Comment by stegm** [comment]
Hi,
This lib is made for Kostal Plenticore, so it might possibly not work at all on the ci.  For the Plenticore it works on the same interface where the web UI is running.

Would be nice to hear if it works or not.

**Comment by Slamkryp** [comment]
Thanks for your reply!I ended up with node-red and modbus and finally got the conversion working.The PIKO ci is a bit Wierd as you can only access the mangement and modbus by Wi-Fi and not ethernet, wich i think is very Wierd from a Securitas standpoint..You can access modbus on rs485 but in a ip world that feels so wrong.Best regardsPatrik EdbergSkickat från min iPhone XIII7 nov. 2023 kl. 18:54 skrev stegm ***@***.***>:﻿
Hi,
This lib is made for Kostal Plenticore, so it might possibly not work at all on the ci.  For the Plenticore it works on the same interface where the web UI is running.
Would be nice to hear if it works or not.
